services:
  # mc_dis_bot:
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   build: .
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   # volumes:
  #   #   - /path/to/logs/latest.log:/app/latest.log:ro

  mc_dis_bot_meetwo:
      extra_hosts:
        - "host.docker.internal:host-gateway"
      build: ./meetwo
      volumes:
        - /home/iwa/mc_server/meetwos/create/logs:/app/logs_create:ro
        - /home/iwa/mc_server/meetwos/sky_greg/logs:/app/logs_sky_greg:ro
      env_file:
        - ./meetwo/.env
      restart: unless-stopped

  mc_dis_bot_test:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./test
    env_file:
      - ./test/.env
    restart: unless-stopped
    # volumes:
    #   - /path/to/logs/latest.log:/app/latest.log:ro