services:
  mc_dis_bot:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    volumes:
      - /home/iwa/mc_server/aero/logs/latest.log:/app/latest.log:ro
    env_file:
      - .env
    restart: unless-stopped
  mc_dis_bot_2_Meetwo:
    build: .
    volumes:
      - /home/iwa/mc_server/meetwo/logs/latest.log:/app/latest.log:ro
    env_file:
      - .env1
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"